### ISSUE TITLE
Can't map easy structure

### ISSUE THREAD

**Issue by nikoncode** [entur/mapstruct-spi-protobuf#137]
Hi.

I am trying to map the following proto structure:
```
message Signed {
  AssetData assets_data = 7;
}

message AssetData {
  repeated AssetItem items = 1;
  AssetZipItem zip_item = 2;
}

message AssetItem {
  string asset_id = 1;
  string asset_title = 2;
}

message AssetZipItem {
  string asset_id = 1;
}
```

with mapper 
```
@Mapper(componentModel = "spring",
        nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
        collectionMappingStrategy = CollectionMappingStrategy.ADDER_PREFERRED)
public interface ProtoDocvaultEventMapper {

    @Mapping(target = "assetsData.zipItem", source = "zipAssetId")
    @Mapping(target = "assetsData.items", source = "signed")
    Signed toSigned(String zipAssetId, List<Asset> signed);

    @Mapping(target = "assetId", source = "asset.id")
    @Mapping(target = "assetTitle", source = "asset.sectionTitle")
    AssetItem toAssetItem(Asset asset);

    @Mapping(target = "assetId", source = "id")
    AssetZipItem toAssetZipItem(String id);
}
```

and got `error: Property "zipItem" has no write accessor in AssetData for target name "assetsData.zipItem".`

So obviously `AssetData.newBuilder().setZipItem()` works perfecltly. Exception looks pretty strange for me.

**Comment by seime** [comment]
@nikoncode Could you provide a complete testcase in the `usage` module? It is impossible for me as is to say whether this is an issue with your mapper, your domain class, mapstruct-spi-protobuf or mapstruct itself.

**Comment by nikoncode** [comment]
@seime thanks for your answer. 

So I simplified my example to https://github.com/nikoncode/mapstruct-issue-demo

Please pay attention that two mapper functions https://github.com/nikoncode/mapstruct-issue-demo/blob/main/app/src/main/java/com/demo/SignedMapper.java#L15 and https://github.com/nikoncode/mapstruct-issue-demo/blob/main/app/src/main/java/com/demo/SignedMapper.java#L19, but it seems that they should.

**Comment by nikoncode** [comment]
Also as you can see from `toSignedNotFail` methods mapping instructions work perfectly if they are not executing together.

**Comment by nikoncode** [comment]
@seime do you have a chance to take a look?

**Comment by seime** [comment]
Unfortunately been unable to follow up on this yet

**Comment by seime** [comment]
I had a look and I do not see what the problem is. A single @Mapping annotation works (as you have done in your example mapper), but when using 2 or more it fails. 

You could ask for mapstruct help at Stackoverflow if you have not solved it yet.

**Comment by seime** [comment]
@nikoncode It is also possible to add a flag to the annotation processor (mapstruct) so it will output more debug messages. Might help you move forward

**Comment by nikoncode** [comment]
@seime I am not sure that we understand each other. I want to build mapstruct mapper which can map two input objects into one output. It's absolutely valid case and mapstruct itself supports it perfectly.

When I am enabling protobuf spi and trying to get protobuf as output for this operation, it stops working completely. 

I can try to provide an example of mapstruct mapper (without protobuf-spi and protobuf intself) which can map two input object into one output and it will work, if it's required.

**Comment by seime** [comment]
I think I understand what you are trying to do. And I do not know why it does not work.

What the mapstruct-spi-protobuf does is to tell mapstruct about _which_ fields, setters, getters etc that are available for mapstruct to use on the protobuf classes. Since this seems to work as long as you provide only _one_ mapping annotation (either one of them), but not when providing _both_ at the same time, my gut feeling is that mapstruct _indeed_ knows about the fields/getters/setters, but seems to get a problem when multiple mapping annotations are combined (and/or there is "deep" field access, ie `data.item.id`).

A working example that does _not_ use protobuf, but have similar _builder_ pattern style might shed some more light on this.

Did you try adding the mapstruct debug flag and examining the output? https://mapstruct.org/documentation/stable/reference/html/#configuration-options

**Comment by esfomeado** [comment]
I'm facing this exact same issue.

It works fine if isn't a protobuf otherwise it fails.
