### ISSUE TITLE
Map array [] element in POJO to List in protobuf

### ISSUE THREAD

**Issue by sharmasha2nk** [entur/mapstruct-spi-protobuf#96]

**Comment by seime** [comment]
This plugin does not generate mapping code, only provides mapstruct with information on which methods and properties that are available

**Comment by njimenezotto** [comment]
Hello, I am having the same issue to achieve that mapping and I don't understand why if mapstuct is able to map from array to list out of the box, why that won't work in this protobuf case.
I have detected that it tries to map the array to the one and only protobuf object instead of the list.

Can't map property "Department[] department" to "UserProtos.DepartmentDTO department". Consider to declare/implement a mapping method: "UserProtos.DepartmentDTO map(Department[] value)".

Maybe, if list to list is working, there is something we ca do to fix this case.

Any traces to find a solution?

Thanks
